 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.6.9
     steps:
       - checkout
       - run: pip install pystrich
       - run: python --version
       - run:
          name: holaa
          command: |
            python hola.py
